// Generated by scripts/charts.py from results/*.json. Do not edit by hand.
window.ESMOE_EFFECT = {
  metrics: ["mAP50", "mAP50-95"],
  rows: [
    {backbone: "yolov5n", arm: "default graft", "mAP50": {mean: 0.0041, seeds: [0.0080, 0.0027, 0.0015], wins: 3}, "mAP50-95": {mean: 0.0026, seeds: [0.0044, 0.0019, 0.0015], wins: 3}},
    {backbone: "yolov5n", arm: "rewire", "mAP50": {mean: 0.0074, seeds: [0.0074], wins: 1}, "mAP50-95": {mean: 0.0062, seeds: [0.0062], wins: 1}},
    {backbone: "yolov8n", arm: "default graft", "mAP50": {mean: 0.0025, seeds: [0.0030, -0.0020, 0.0066], wins: 2}, "mAP50-95": {mean: 0.0004, seeds: [-0.0002, -0.0015, 0.0028], wins: 1}},
    {backbone: "yolov8n", arm: "rewire", "mAP50": {mean: 0.0036, seeds: [0.0090, 0.0012, 0.0007], wins: 3}, "mAP50-95": {mean: 0.0011, seeds: [0.0033, -0.0003, 0.0005], wins: 2}},
    {backbone: "yolo11n", arm: "default graft", "mAP50": {mean: 0.0013, seeds: [0.0028, 0.0027, -0.0015], wins: 2}, "mAP50-95": {mean: 0.0001, seeds: [0.0032, -0.0010, -0.0020], wins: 1}},
    {backbone: "yolo11n", arm: "rewire", "mAP50": {mean: 0.0004, seeds: [0.0008, -0.0071, 0.0076], wins: 2}, "mAP50-95": {mean: 0.0002, seeds: [-0.0003, -0.0025, 0.0035], wins: 1}},
    {backbone: "yolo12n", arm: "default graft", "mAP50": {mean: -0.0018, seeds: [-0.0022, -0.0026, -0.0007], wins: 0}, "mAP50-95": {mean: -0.0021, seeds: [-0.0032, -0.0028, -0.0002], wins: 0}},
    {backbone: "yolo12n", arm: "rewire", "mAP50": {mean: 0.0001, seeds: [0.0012, -0.0028, 0.0019], wins: 2}, "mAP50-95": {mean: 0.0006, seeds: [0.0011, -0.0010, 0.0016], wins: 2}},
    {backbone: "yolo26n", arm: "default graft", "mAP50": {mean: -0.0034, seeds: [-0.0057, -0.0035, -0.0010], wins: 0}, "mAP50-95": {mean: -0.0022, seeds: [-0.0022, -0.0031, -0.0011], wins: 0}},
    {backbone: "yolo26n", arm: "rewire", "mAP50": {mean: -0.0005, seeds: [-0.0033, -0.0008, 0.0026], wins: 1}, "mAP50-95": {mean: 0.0008, seeds: [0.0006, -0.0001, 0.0019], wins: 2}}
  ]
};
