// Generated by scripts/charts.py from results/*.json. Do not edit by hand.
window.ESMOE_EFFECT = {
  metrics: ["mAP50", "mAP50-95"],
  rows: [
    {backbone: "yolov5n", arm: "default graft", "mAP50": {mean: 0.0055, seeds: [0.0052, 0.0004, 0.0109], wins: 3}, "mAP50-95": {mean: 0.0038, seeds: [0.0052, 0.0001, 0.0061], wins: 3}},
    {backbone: "yolov5n", arm: "rewire", "mAP50": {mean: 0.0024, seeds: [0.0042, -0.0010, 0.0039], wins: 2}, "mAP50-95": {mean: 0.0018, seeds: [0.0037, -0.0019, 0.0036], wins: 2}},
    {backbone: "yolov8n", arm: "default graft", "mAP50": {mean: 0.0025, seeds: [0.0030, -0.0020, 0.0066], wins: 2}, "mAP50-95": {mean: 0.0004, seeds: [-0.0002, -0.0015, 0.0028], wins: 1}},
    {backbone: "yolov8n", arm: "rewire", "mAP50": {mean: 0.0036, seeds: [0.0090, 0.0012, 0.0007], wins: 3}, "mAP50-95": {mean: 0.0011, seeds: [0.0033, -0.0003, 0.0005], wins: 2}},
    {backbone: "yolov9t", arm: "default graft", "mAP50": {mean: 0.0025, seeds: [0.0019, 0.0081, -0.0025], wins: 2}, "mAP50-95": {mean: 0.0009, seeds: [0.0007, 0.0035, -0.0016], wins: 2}},
    {backbone: "yolov9t", arm: "rewire", "mAP50": {mean: -0.0013, seeds: [-0.0058, -0.0022, 0.0040], wins: 1}, "mAP50-95": {mean: -0.0021, seeds: [-0.0051, -0.0035, 0.0023], wins: 1}},
    {backbone: "yolov10n", arm: "default graft", "mAP50": {mean: -0.0002, seeds: [0.0007, -0.0029, 0.0021, -0.0010, 0.0002], wins: 3}, "mAP50-95": {mean: -0.0003, seeds: [-0.0003, -0.0020, 0.0007, 0.0000, -0.0003], wins: 2}},
    {backbone: "yolov10n", arm: "rewire", "mAP50": {mean: -0.0031, seeds: [-0.0000, -0.0081, 0.0058, -0.0088, -0.0046], wins: 1}, "mAP50-95": {mean: -0.0016, seeds: [-0.0013, -0.0054, 0.0049, -0.0044, -0.0020], wins: 1}},
    {backbone: "yolo11n", arm: "default graft", "mAP50": {mean: 0.0013, seeds: [0.0028, 0.0027, -0.0015], wins: 2}, "mAP50-95": {mean: 0.0001, seeds: [0.0032, -0.0010, -0.0020], wins: 1}},
    {backbone: "yolo11n", arm: "rewire", "mAP50": {mean: 0.0004, seeds: [0.0008, -0.0071, 0.0076], wins: 2}, "mAP50-95": {mean: 0.0002, seeds: [-0.0003, -0.0025, 0.0035], wins: 1}},
    {backbone: "yolo12n", arm: "default graft", "mAP50": {mean: -0.0018, seeds: [-0.0022, -0.0026, -0.0007], wins: 0}, "mAP50-95": {mean: -0.0021, seeds: [-0.0032, -0.0028, -0.0002], wins: 0}},
    {backbone: "yolo12n", arm: "rewire", "mAP50": {mean: 0.0001, seeds: [0.0012, -0.0028, 0.0019], wins: 2}, "mAP50-95": {mean: 0.0006, seeds: [0.0011, -0.0010, 0.0016], wins: 2}},
    {backbone: "yolo26n", arm: "default graft", "mAP50": {mean: -0.0034, seeds: [-0.0057, -0.0035, -0.0010], wins: 0}, "mAP50-95": {mean: -0.0022, seeds: [-0.0022, -0.0031, -0.0011], wins: 0}},
    {backbone: "yolo26n", arm: "rewire", "mAP50": {mean: -0.0005, seeds: [-0.0033, -0.0008, 0.0026], wins: 1}, "mAP50-95": {mean: 0.0008, seeds: [0.0006, -0.0001, 0.0019], wins: 2}}
  ],
  alignment: [
    {backbone: "yolov10n", arm: "e4k2w0.01-norm", mean: 0.0001, ci: "-", seeds: [0.0001], wins: 1},
    {backbone: "yolov10n", arm: "e4k2w0.01-rewire-x4", mean: -0.0071, ci: "[-0.0162, +0.0019]", seeds: [-0.0055, -0.0113, -0.0046], wins: 0},
    {backbone: "yolov5n", arm: "e4k2w0.01-dense", mean: 0.0031, ci: "[-0.0006, +0.0068]", seeds: [0.0020, 0.0025, 0.0048], wins: 3},
    {backbone: "yolov5n", arm: "e4k2w0.01-gshard", mean: 0.0018, ci: "[-0.0409, +0.0445]", seeds: [0.0051, -0.0016], wins: 1},
    {backbone: "yolov5n", arm: "e4k2w0.01-norm", mean: 0.0038, ci: "[-0.0033, +0.0109]", seeds: [0.0006, 0.0047, 0.0061], wins: 3}
  ]
};
