"""How hard each balancing term actually pushes, at the operating points real checkpoints reached.

Comparing the terms by their value is misleading: they differ by constants and sit at different
floors. What decides how much a weight buys is the gradient the term puts on the router's logits,
so that is what this measures -- around the mean routing probabilities a checkpoint actually
converged to, at several spreads, because the answer depends on where the router is.

    uv run python scripts/pressure.py
"""

import json
import sys
from pathlib import Path

import torch

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from routing import normalise  # noqa: E402

from esmoe.module import gshard_balance, gshard_probs_balance, master_balance, switch_balance  # noqa: E402

TERMS = (
    ("switch", switch_balance),
    ("gshard_probs", gshard_probs_balance),
    ("gshard(gate)", gshard_balance),
    ("master", master_balance),
)
SPREADS = (0.15, 0.5, 1.5)
IMAGES = 548


def gate_of(probs: torch.Tensor, top_k: int = 2) -> torch.Tensor:
    weights, chosen = probs.topk(top_k, dim=1)
    gate = torch.zeros_like(probs).scatter(1, chosen, weights)
    return gate / gate.sum(dim=1, keepdim=True)


def gradients(mean: torch.Tensor, spread: float) -> list[float]:
    """Mean |d term / d logit| for each term, at logits scattered around ``mean``."""
    torch.manual_seed(0)
    logits = (mean.log().repeat(IMAGES, 1) + spread * torch.randn(IMAGES, len(mean))).requires_grad_(True)
    found = []
    for _, term in TERMS:
        logits.grad = None
        probs = logits.softmax(dim=1)
        term(probs, gate_of(probs)).backward()
        found.append(logits.grad.abs().mean().item())
    return found


def main() -> int:
    records = sorted((ROOT / "results" / "routing").glob("*.json"))
    if not records:
        print("no routing records; run scripts/routing.py first")
        return 1

    rows = []
    for path in records:
        block = normalise(json.loads(path.read_text(encoding="utf-8")))["blocks"][0]
        if len(block["mean_prob"]) != 4:
            continue
        mean = torch.tensor(block["mean_prob"])
        for spread in SPREADS:
            rows.append((path.stem, spread, gradients(mean, spread)))

    names = [name for name, _ in TERMS]
    lines = [
        "# Balancing pressure per unit weight",
        "",
        "Mean |d term / d logit| at the mean routing probabilities each checkpoint converged to,",
        f"over {IMAGES} rows scattered by the spread column. Generated by `scripts/pressure.py`.",
        "",
        "| checkpoint | spread | " + " | ".join(names) + " | gate/switch |",
        "|:--|:--:|" + "--:|" * (len(names) + 1),
    ]
    for stem, spread, found in rows:
        ratio = found[2] / found[0] if found[0] else float("inf")
        cells = " | ".join(f"{g:.3e}" for g in found)
        lines.append(f"| {stem} | {spread} | {cells} | {ratio:.2f} |")

    ratios = [found[2] / found[0] for _, _, found in rows if found[0]]
    against = [found[3] / found[0] for _, _, found in rows if found[0]]
    lines += [
        "",
        f"Reading the gate costs {min(ratios):.2f}x to {max(ratios):.2f}x what the Switch term costs at the "
        f"same weight, so the two arms are pushed comparably hard; the paper's form is "
        f"{1 / max(against):.0f}x to {1 / min(against):.0f}x weaker, which is the `1/E^2` factor.",
    ]
    text = "\n".join(lines) + "\n"
    (ROOT / "results" / "pressure.md").write_text(text, encoding="utf-8")
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
